#ifndef PLUGINMENUFILE_GLOBAL_H
#define PLUGINMENUFILE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PLUGINMENUFILE_LIB
# define PLUGINMENUFILE_EXPORT Q_DECL_EXPORT
#else
# define PLUGINMENUFILE_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINMENUFILE_GLOBAL_H
